- .travis.yml
Note current `master`branch build can fail with `ruby-head`.
We might allow failling with `ruby-head` on Travis.
> Test on new Ruby versions

- test/fiddle/test_import.rb
This commit fixes the following failure:
```
1) Failure:
Fiddle::TestImport#test_no_message_with_debug [/Users/mrkn/src/github.com/ruby/fiddle/test/fiddle/test_import.rb:152]:
1. [2/2] Assertion for "stderr"
| <[]> expected but was
| <["Exception `NameError' at /Users/mrkn/.rbenv/versions/2.5.1/lib/ruby/2.5.0/fiddle/import.rb:157 - uninitialized constant Fiddle::Function::STDCALL"]>.
```
> Fix a failing test

- test/fiddle/helper.rb
The following code is wrong some platforms, e.g., mswin/mingw.
```ruby
case [0].pack('L!').size
when 4
when 8
end
```
> Use RbConfig::SIZEOF

- ext/fiddle/closure.c
- ext/fiddle/extconf.rb
TLDR; Set ```USE_FFI_CLOSURE_ALLOC=1``` by default for better compatibility and improved SELinux support [[3]]
Recently, we were trying to build Ruby 2.6 on RHEL8, but with the most recent version of libffi including patch for https://github.com/libffi/libffi/issues/470, we started to observe crashes on AArch64 such as:
~~~
... snip ...
making mjit_build_dir.so
/builddir/build/BUILD/ruby-2.6.3/.ext/common/fiddle/import.rb:317: [BUG] Segmentation fault at 0x0000000000000018
ruby 2.6.3p62 (2019-04-16 revision 67580) [aarch64-linux]
-- Control frame information -----------------------------------------------
c:0018 p:---- s:0103 e:000102 CFUNC  :initialize
c:0017 p:---- s:0100 e:000099 CFUNC  :new
c:0016 p:0047 s:0093 e:000092 METHOD …
> Use ffi_closure_free by default.

- ext/fiddle/function.c
- ext/fiddle/handle.c
- ext/fiddle/pointer.c
- test/fiddle/test_func.rb
- test/fiddle/test_function.rb
- test/fiddle/test_handle.rb
- test/fiddle/test_pointer.rb
Ruby 2.7 deprecates taint and it no longer has an effect.
The lack of taint support should not cause a problem in
previous Ruby versions.
> Remove taint support

- ext/fiddle/fiddle.c
This pull request was split from #14 as requested by @nobu .
When calling `Fiddle.malloc`, the contents of the resulting memory were not initialized to 0 as they were when calling `Fiddle::Pointer.malloc`. This inconsistency led to unexpected and difficult-to-debug behavior.
> Initialize memory to 0 when calling Fiddle.malloc().

- lib/fiddle/struct.rb
- test/fiddle/test_import.rb
This pull request was split from #14 as requested by @nobu .
`CStructEntity` defines array subscript methods (`[]` / `[]=`), which is fine except that they override `Fiddle::Pointer#[]` and `Fiddle::Pointer#[]=` and do not handle the 3rd argument that the base class allows for. The methods from `Fiddle::Pointer` provide for direct manipulation of the underlying memory, but this ability is lost in `CStructEntity` because the superclass methods are not available in the subclass (ignoring ugly hacks like `Fiddle::Pointer.method(:[]).unbind.bind(struct).call`). This pull request modifies the overridden methods to check for an additional argument which would be understood by `super`. If the extra argument is provided, `super` is called so that the underlying memory can be accessed / assigned …
> Make array access override compatible with base class

- lib/fiddle/struct.rb
- test/fiddle/test_import.rb
This pull request was split from #14 as requested by @nobu . It depends on #25 because that pull request makes it possible to access the underlying memory of a struct, which is required in order for this pull request to work properly.
When a member of a struct is an array, `CStructEntity` would return a temporary array containing those values. Assignment to that array was a no-op, which led to confusing behavior because an assignment to the array would be "ignored". I fixed this so that assignment to the returned array correctly updates the member within the struct.
For example:
```ruby
a = struct(['int i[5]']).malloc
a.i[2] = 1 # previously, this would do nothing
a.i[2] #=> 1
```
> Fix assignment to array within struct

- ext/fiddle/pointer.c
- lib/fiddle/struct.rb
- test/fiddle/test_c_struct_entry.rb
- test/fiddle/test_c_union_entity.rb
- test/fiddle/test_import.rb
- test/fiddle/test_pointer.rb
The documentation for pointers and structs doesn't include as much helpful information as it could about who is responsible for freeing memory and how to do it safely. I've added some specific examples for guidance.
I've then also applied this in the test suite, which I think was not freeing memory in many tests.
Or am I misunderstanding how freeing pointers and structs works in Fiddle?
If I'm understanding it all correctly, I'd then like to follow this up with some additions to the API to make it even easier to do the right thing, such as
```ruby
Fiddle::Pointer.malloc(size) do |pointer|
...
end
```
```ruby
pointer = Fiddle::Pointer.malloc(size)
pointer.free_now
```
```ruby
pointer = Fiddle::Pointer.malloc(size, free_routine)
pointer.free_now
```
> Improve documentation on how to correctly free memory and free memory in tests

- .github/workflows/fiddle.yml
Today the ruby head mswin build broke from fiddle.  ruby/ruby appears to download libffi 3.2.1 for the mswin build, but 3.3 is vendored here.
I started here and created a GitHub Actions workflow, covering Ruby 2.3 thru master/head for Ubuntu, macOS, and Windows.  All are passing except Windows mswin.   I did add a compile step just to see what was happening.
This may not run, as often the first PR with a GHA workflow doesn't.  A link to a run in my fork is:
https://github.com/MSP-Greg/fiddle/actions/runs/116195157
> Add GH Actions

- .github/workflows/fiddle.yml
Since we're testing a default gem, disabling RubyGems is probably a good idea, especially since the test files are vendored.
Also, MinGW build's devkit requires fiddle, so that causes issues.
> Fix Actions - test step - --disable=gems

- ext/fiddle/pointer.c
- test/fiddle/test_pointer.rb
`free!` runs the user's free function. It doesn't do anything if the pointer has already been freed. The GC won't call the user's free function if the user already manually freed. Another method `freed?` tells the user if the pointer has already been freed.
All together, these changes allow you to rely on the GC to definitely free your memory, meaning no leaks, but then also allows you to manually free as early as possible if you can, meaning deterministic deallocation, improving cache locality and and reducing peaks in memory use.
> Add a Fiddle::Pointer#call_free method

- ext/fiddle/pointer.c
- test/fiddle/test_c_struct_entry.rb
- test/fiddle/test_pointer.rb
```ruby
Fiddle::Pointer.new(size, free) do |pointer|
...
end
```
* Easy to use best-practice
* Helps people write correct code for the most common cases
* Protect against leaks (free if there's an exception, or even if someone uses a trace point to get hold of the object)
* Protect against deallocation latency (free as soon as you're done)
* Protect against non-locality (free while it's still in cache from your using it)
> Structured memory deallocation using blocks

- ext/fiddle/pointer.c
- lib/fiddle/struct.rb
- test/fiddle/test_c_struct_entry.rb
- test/fiddle/test_c_union_entity.rb
- test/fiddle/test_import.rb
- test/fiddle/test_pointer.rb
Allows you to go from
```ruby
struct = CStructEntity.malloc([TYPE_INT, TYPE_LONG])
begin
...
ensure
Fiddle.free struct
end
```
to
```ruby
CStructEntity.malloc([TYPE_INT, TYPE_LONG], Fiddle::RUBY_FREE) do |struct|
..
end
```
and from
```ruby
timeval = LIBC::Timeval.malloc()
begin
timezone = LIBC::Timezone.malloc()
begin
LIBC.gettimeofday(timeval, timezone)
ensure
Fiddle.free timezone.to_ptr
end
ensure
Fiddle.free timeval.to_ptr
end
```
to
```ruby
LIBC::Timeval.malloc(Fiddle::RUBY_FREE) do |timeval|
LIBC::Timezone.malloc(Fiddle::RUBY_FREE) do |timezone|
LIBC.gettimeofday(timeval, timezone)
end
end
```
Both are safer, have better temporal and spatial locality for the memory manager, and reduce the working set size.
> Add new pointer memory management interfaces to structs and unions

- .github/workflows/fiddle.yml
Can we remove this failing job, and put it back in a PR where we get it working before merging it?
> mswin CI job doesn't work - remove it

- ext/fiddle/fiddle.c
- ext/fiddle/fiddle.h
- ext/fiddle/handle.c
- ext/fiddle/pinned.c
- ext/fiddle/pointer.c
- fiddle.gemspec
- test/fiddle/test_pinned.rb
A `Fiddle::Pinned` objects will prevent the objects they point to from
moving.  This is useful in the case where you need to pass a reference
to a C extension that keeps the address in a global and needs the
address to be stable.
For example:
```ruby
class Foo
A = "hi" # this is an embedded string
some_c_function A # A might move!
end
```
If `A` moves, then the underlying string buffer may also move.
`Fiddle::Pinned` will prevent the object from moving:
```ruby
class Foo
A = "hi" # this is an embedded string
A_pinner = Fiddle::Pinned.new(A) # :nodoc:
some_c_function A # A can't move because of `Fiddle::Pinned`
end
```
This is a similar strategy to what Graal uses:
https://www.graalvm.org/sdk/javadoc/org/graalvm/nativeimage/PinnedObject.html#getObject--
> Add a "pinning" reference

- ext/fiddle/function.c
Since Fiddle::Function releases the GVL when making the call, it's not
thread-safe to use it to call a lot of Ruby's C extension APIs.
---
I want to warn against this because I had to debug a thread safety issue caused by this. [Rutie](https://github.com/danielpclark/rutie) uses Fiddle to call the init function of C extensions that it produces, which is not thread-safe without the GVL.
See:
https://github.com/danielpclark/rutie/blob/master/examples/rutie_ruby_gvl_example/lib/rutie_ruby_gvl_example.rb#L5
https://github.com/danielpclark/rutie-gem/blob/ffaba4689f351a0acaf84067a6fca5c3b65bc9aa/lib/rutie.rb#L21
> Warn against using Fiddle::Function to call C extension APIs

- test/fiddle/helper.rb
Because macOS 11.0(Big Sur) was removed libc and libm from `/usr/lib`.
~https://github.com/ruby/ruby/commit/bd47a8d660~
https://github.com/ruby/ruby/commit/b7d86e330c
https://github.com/ruby/ruby/commit/cdef17096c
https://github.com/ruby/ruby/commit/0168094da2
> Use libSystem.B.dylib instead of libm.dylib and libc.dylib

- ext/fiddle/extconf.rb
`-I$(top_srcdir)` is unnecessary because fiddle no longer depends on ruby's internal.h.
`top_srcdir` is not defined when fiddle will be installed as a gem.  In that situation, `-I$(top_srcdir)` turns to be `-I`, so the next compiler option is consumed as an argument of `-I`.
> Remove -I$(top_srcdir)

- test/fiddle/helper.rb
> Do not use a libdir for glibc, it breaks Linux PPC64

- ext/fiddle/memory_view.c
- test/fiddle/test_memory_view.rb
fix #79
Users can release memory views explicitly before process exit.
Reported by xtkoba. Thanks!!!
> Add MemoryView.export and MemoryView#release

- lib/fiddle/struct.rb
- test/fiddle/test_c_struct_builder.rb
I need to get the offset of a member inside a struct without allocating
the struct.  This patch adds an "offsetof" class method to structs that
are generated.
The usage is like this:
```ruby
MyStruct = struct [
"int64_t i",
"char c",
]
MyStruct.offsetof("i") # => 0
MyStruct.offsetof("c") # => 8
```
> Add "offsetof" to Struct classes

- ext/fiddle/fiddle.h
- ext/fiddle/handle.c
- ext/fiddle/pointer.c
- test/fiddle/test_handle.rb
`Fiddle::Handle#to_i` currently returns the address of the value of the module handle, that is `&fiddle_handle->ptr`.
I guess it is more useful than now that it returns the value of the module handle directly.
> Return the module handle value in Fiddle::Handle#to_i

- ext/-test-/memory_view/extconf.rb
- ext/-test-/memory_view/memory_view.c
- ext/fiddle/fiddle.c
- ext/fiddle/fiddle.h
- ext/fiddle/memory_view.c
- ext/fiddle/pointer.c
These macros are defined for exactly this purpose.
> Check HAVE_RUBY_MEMORY_VIEW_H rather than API version

- ext/fiddle/extconf.rb
- ext/fiddle/fiddle.h
- ext/fiddle/handle.c
- test/fiddle/test_handle.rb
Use `GetModuleFileName` or `dlinfo` to obtain the file name of `Fiddle::Handle` object.
> Add Fiddle::Handle#file_name

- lib/fiddle/struct.rb
- test/fiddle/test_c_struct_builder.rb
I need to get the offset of members inside sub structures.  This patch
adds sub-structure offset support for structs.
> Improve "offsetof" calculations

- test/fiddle/helper.rb
> Fix filenames for glibc SO files on alpha and ia64

- ext/fiddle/closure.c
- ext/fiddle/conversions.c
- ext/fiddle/fiddle.c
- ext/fiddle/fiddle.h
- lib/fiddle/cparser.rb
- lib/fiddle/pack.rb
- test/fiddle/test_import.rb
This commit adds constants for unsigned values.  Currently we can use `-` to mean "unsigned", but I think having a specific name makes Fiddle more user friendly.  This commit continues to support `-`, but introduces negative constants with "unsigned" names
I think this will help to eliminate [this code](https://github.com/ruby/ruby/blob/3a56bf0bcc66e14ffe5ec89efc32ecfceed180f4/lib/mjit/c_type.rb#L31-L38)
> Add constants for unsigned values

- ext/fiddle/fiddle.c
- lib/fiddle.rb
- test/fiddle/test_import.rb
This helps to reduce repetition in code.  Instead of doing "TYPE_*" everywhere, you can do `include Fiddle::Types`, and write the type name directly.
This PR is to help reduce repetition when writing Fiddle code.  Right now we have to type `TYPE_` everywhere, and you also have to include all of `Fiddle` to access `TYPE_*` constants.  With this change, you can just include `Fiddle::Types` and it will shorten your code and also you only have to include those constants.
Here is an example before:
```ruby
module MMAP
include Fiddle
def self.make_function name, args, ret
ptr = Handle::DEFAULT[name]
func = Function.new ptr, args, ret, name: name
define_singleton_method name, &func.to_proc
end
make_function "munmap", [TYPE_VOIDP, # addr
TYPE_SIZE_T], # len
TYPE_INT
make_function …
```
> Move "type" constants to `Fiddle::Types`

- lib/fiddle/value.rb
String#unpack1 is available since Ruby 2.4, and support for older than Ruby 2.5 was dropped by #85. 
Also simplified a common return statement.
> Prefer String#unpack1 in Fiddle::ValueUtil

- ext/fiddle/fiddle.h
WG14 N2350 made very clear that it is an UB having type definitions within "offsetof" [1]. This patch enhances the implementation of macro ALIGN_OF to use builtin "_Alignof" to avoid undefined behavior when using std=c11 or newer
clang 16+ has started to flag this [2]
Fixes build when using -std >= gnu11 and using clang16+
Older compilers gcc < 4.9 or clang < 8 has buggy _Alignof even though it may support C11, exclude those compiler versions
[1] https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2350.htm [2] https://reviews.llvm.org/D133574
Signed-off-by: Khem Raj <raj.khem@gmail.com>
> fiddle: Use C11 _Alignof to define ALIGN_OF when possible

- .github/workflows/ci.yml
`macos-10.05` will be removed by 2023-03-31.
> Remove macos-10.05 image

- ext/fiddle/pointer.c
- test/fiddle/test_pointer.rb
This commit adds two new methods, `Fiddle::Pointer.read` and `Fiddle::Pointer.write`.  Both methods take an address, and will read or write bytes at that address respectively.
For example we can read from an address without making a Pointer object:
```ruby
Fiddle::Pointer.read(address, 5) # read 5 bytes
```
We can also write to an address without allocating a Pointer object:
```ruby
Fiddle::Pointer.write(address, "bytes") # write 5 bytes
```
This allows us to read / write memory at arbitrary addresses without instantiating a new `Fiddle::Pointer` object.
Examples where this API would be useful [1](https://github.com/tenderlove/tenderjit/blob/f03481d28bff4d248746e596929b0841de65f181/lib/tenderjit/fiddle_hacks.rb#L26-L28) [2](https://github.com/tenderlove/ruby/blob/77c8daa2d40dd58eeb3785ce17 …
> Add a helper method for reading/writing memory

- ext/fiddle/closure.c
- ext/fiddle/function.c
- ext/fiddle/handle.c
They don't have a mark function, so they don't need any change.
> Mark Closure, Function and Handle as write barrier protected

- ext/fiddle/extconf.rb
```
In file included from ../../../../ext/fiddle/fiddle.h:46:
/opt/local/include/ffi.h:477:5: warning: 'FFI_GO_CLOSURES' is not defined, evaluates to 0 [-Wundef]
^
```
c.f. https://github.com/libffi/libffi/pull/796
> Suppress -Wundef warnings on arm64 macOS and Windows

- .github/workflows/ci.yml
- docker-compose.yml
- dockerfiles/fedora-latest.dockerfile
macos-11 (Big Sur) is EOL today. I removed it and add `macos-arm-oss` instead of `macos-11`. `macos-arm-oss` is `macos-13` with Apple Silicon architecture. We can cover with them for real world usage.
> Use macos-arm-oss instead of macos-11

- fiddle.gemspec
This PR added [changelog_uri](https://guides.rubygems.org/specification-reference/#metadata) for [rubygems.org](https://rubygems.org/gems/fiddle)
> Set changelog_uri gem metadata

- ext/fiddle/closure.c
- ext/fiddle/conversions.c
- ext/fiddle/fiddle.c
- ext/fiddle/fiddle.h
- ext/fiddle/function.c
- ext/fiddle/handle.c
Some of these commands just don't work (for example `sws` is not a Vim setting). I think we should just remove these.
> Remove Vim commands

- .github/workflows/ci.yml
Unfortunately, we lost macos-arm-oss runner from ruby org.
> Use macos-14 instead of macos-arm-oss

- ext/fiddle/function.c
- ext/fiddle/pointer.c
With gcc 13 and -pedantic:
```
../../../src/ext/fiddle/function.c: In function ‘function_call’:
../../../src/ext/fiddle/function.c:374:15: error: ISO C forbids conversion of object pointer to function pointer type [-Wpedantic]
374 |     args.fn = (void(*)(void))NUM2PTR(cfunc);
|               ^
../../../src/ext/fiddle/pointer.c: In function ‘rb_fiddle_ptr_inspect’:
../../../src/ext/fiddle/pointer.c:573:84: error: ISO C forbids conversion of function pointer to object pointer type [-Wpedantic]
573 |                       RB_OBJ_CLASSNAME(self), (void *)data, data->ptr, data->size, (void *)data->free);
|                                                                                    ^
```
> Cast via `VALUE` function pointer between object pointer

- test/fiddle/helper.rb
The test of current HEAD revision occurred `unknown command` on `ruby/ruby` repo.
```
$ make test-all -j TESTS="fiddle -j12" MSPECOPT="-j"
(snip)
unknown command: "Fiddle::VERSION: 1.1.3.dev"8681=test_fiddle 58682=test_pack 58683=test_handle 58684=test_import 58685=test_c_union_entity 58686:waiting 58687=test_pinne
unknown command: "Fiddle::VERSION: 1.1.3.dev"8681=test_fiddle 58682=test_pack 58683=test_handle 58684=test_import 58685=test_c_union_entity 58686=test_cparser 58687=test_
unknown command: "Fiddle::VERSION: 1.1.3.dev"8681=test_fiddle 58682=test_pack 58683=test_handle 58684=test_import 58685=test_c_union_entity 58686=test_cparser 58687=test_
unknown command: "Fiddle::VERSION: 1.1.3.dev"8681=test_fiddle 58682=test_memory_view 58683=test_handle 58684=test_import …
```
> Only print Fiddle::VERSION when flag is true

- lib/fiddle/ffi_backend.rb
- test/fiddle/test_handle.rb
* From https://github.com/ruby/reline/issues/766#issuecomment-2422135968
cc @headius
> Fix Fiddle::Handle.new for a missing library in the FFI backend

- ext/fiddle/extconf.rb
- ext/fiddle/fiddle.h
The GCC warning puts undefined macro names in double quotes while clang puts them in single quotes.
> Suppress -Wundef warnings

- ext/fiddle/extconf.rb
GitHub: fix GH-153
mkmf requires fileutils. JRuby doesn't like it.
> Don't use mkmf to generate dummy Makefile

- test/fiddle/test_fiddle.rb
I found working on Fedora 40 on aarch64 that  `test_dlopen_linker_script_input_linux` was omitted due to not finding libncurses.so, since it is in /usr/lib64. This PR makes the glob a little more portable.
> Fix test_dlopen_linker_script_input_linux being omitted on Fedora 40 aarch64

- ext/fiddle/pointer.c
Pick https://github.com/ruby/ruby/commit/6adc69c41c6edb409c5306573511cd6d8b436fbe
```
Do not depend on the evaluation order of C arguments
The evaluation order of C arguments is unspecified. `RSTRING_LEN(str)` would fails if the conversion to a String by `StringValuePtr` is not done yet.
Coverity Scan found this issue.
```
> Forward-port from ruby/ruby

- lib/fiddle/ffi_backend.rb
- test/fiddle/test_function.rb
- test/fiddle/test_pointer.rb
This allows for passing integers as pointer arguments to functions when using the FFI backend. This is a workaround until we can get JRuby's FFI implementation to allow for it directly (see also https://github.com/jruby/jruby/pull/8423)
> ffi_backend: convert numeric function args to pointers

- lib/fiddle/cparser.rb
- test/fiddle/test_cparser.rb
GitHub: fix GH-168
Struct parsing invokes "parse_ctype" on the whole member signature, which fails if member type is "bool" due to plain string matching for it. This change updates "bool" type matching to a regexp, so TYPE_BOOL is correctly parsed for a whole signature like "bool toggle" as well as just "bool".
> add regex for bool parsing & test struct w/ bool parsing

- lib/fiddle.rb
`RUBY_ENGINE` and `Fiddle::WINDOWS` should not change in a process, no need to be checked inside the methods.
Also, `win32_last_error` and `win32_last_socket_error` are equal to `last_error` on JRuby.
> Define Fiddle.last_error family and Fiddle.dlopen statically

- lib/fiddle/ffi_backend.rb
- test/fiddle/test_pointer.rb
Hi, this PR makes the behavior of `Fiddle::Pointer#to_s` consistent between CRuby and JRuby.
```ruby
ptr = Fiddle::Pointer.malloc(4)
p ptr.to_s(4)
```
currently outputs `"\x00\x00\x00\x00"` with CRuby and `""` with JRuby.
> Make `Fiddle::Pointer#to_s` with JRuby consistent with CRuby

- test/fiddle/test_fiddle.rb
In Debian alpha architecture, we have libc.so.6.1 which causes a failure in this test:
1) Failure:
TestFiddle#test_dlopen_linker_script_group_linux [/<<PKGBUILDDIR>>/test/fiddle/test_fiddle.rb:52]:
<"libc.so"> expected but was
<"libc.so.6">.
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1085238
> Fix test dlopen for libc.so filename with more than one digit

- lib/fiddle/ffi_backend.rb
- test/fiddle/test_pointer.rb
```ruby
p Fiddle::Pointer.new(1)
```
CRuby
```text
#<Fiddle::Pointer:0x0000600000983240 ptr=0x0000000000000001 size=0 free=0x0000000000000000>
```
JRuby before
```text
#<Fiddle::Pointer ptr=1 size=9223372036854775807 free=nil>
```
JRuby after
```text
#<Fiddle::Pointer ptr=0x0000000000000001 size=9223372036854775807 free=0x0000000000000000>
```
Note: `size` is incorrect for JRuby, which is not addressed with this PR
> Improve `Fiddle::Pointer#inspect` for FFI backend

- lib/fiddle/ffi_backend.rb
To reproduce with JRuby or TruffleRuby:
```ruby
1000.times do
Fiddle::Pointer[rand(255).chr*16]
end
```
`put_string` adds a null byte at the end vs `write_bytes`. This is not caught by the bounds check since the underlying `FFI::Pointer` size is not set.
> Fix memory corruption with FFI backend

- lib/fiddle/ffi_backend.rb
- test/fiddle/test_closure.rb
Currently, pointer arguments for closures use the FFI pointer class instead of the Fiddle pointer class with the FFI backend.
> Fix pointer class for closure arguments for FFI backend

- lib/fiddle/ffi_backend.rb
- test/fiddle/test_pointer.rb
This PR makes the pointer size consistent between backends. Follow up to #179.
```ruby
ptr = Fiddle::Pointer.new(0)
p ptr.size
p ptr.ref.size
ptr = Fiddle::Pointer["hello world"]
ptr.size = 0
p ptr.to_s
p ptr.to_str
```
JRuby + TruffleRuby before
```text
9223372036854775807
8
""
""
```
CRuby + JRuby + TruffleRuby after
```text
0
0
"hello world"
""
```
> Make pointer size consistent between backends

- lib/fiddle/ffi_backend.rb
- test/fiddle/test_pointer.rb
Also added more tests for the current behavior.
```ruby
ptr = Fiddle::Pointer["hello\0world"]
ptr.size = 0
p (ptr + 1).size
p (ptr + 1).to_s(5)
p (ptr + 1).to_s
p (ptr + 1).to_str(5)
p (ptr + 1).to_str
```
Output
```text
-1
"ello\x00"
"ello"
"ello\x00"
repro.rb:10:in 'Fiddle::Pointer#to_str': negative string size (or size too big) (ArgumentError)
```
> Make `to_str` consistent between backends for negative pointer sizes

- lib/fiddle/ffi_backend.rb
- test/fiddle/test_pointer.rb
Fixes #182 by making the pointer address dynamic.
```ruby
ptr = Fiddle::Pointer["hello"]
ptr.ref[0, Fiddle::SIZEOF_VOIDP] = Fiddle::Pointer["world"].ref
p ptr.to_s
```
The code above previously returned `"hello"` with the FFI backend.
> Fix `Fiddle::Pointer#ref` behavior for FFI backend

- lib/fiddle/ffi_backend.rb
- test/fiddle/test_pointer.rb
Addresses https://github.com/ruby/fiddle/pull/180#discussion_r2059164448
> Restore null byte in to_ptr for FFI backend

- test/fiddle/test_pointer.rb
```
test/fiddle/test_pointer.rb:288: warning: ambiguous first argument;
put parentheses or a space even after '-' operator
```
I noticed this in one of my ruby builds: https://github.com/ruby/ruby/actions/runs/14838247932/job/41654544867?pr=13159#step:8:1818
cc @kou @ankane
> Fix "ambiguous first argument" warning in test suite

- .github/workflows/ci.yml
This PR is working in progress to add GitHub Actions Ubuntu 24.04 ppc64le/s390x cases. This is one of the tasks that we add the cases in some ruby/* repositories. The task is tracked at https://github.com/IBM/actionspz/issues/4#issuecomment-3109205041.
Maybe, this PR's change will be for only `.github/workflows/ci.yml`, while you see other changes in other files temporarily to work on this PR easily for now. I needed to sent a PR to this repository to test the ppc64le/s390x CI pipelines, rather than to test on my fork repository because GitHub Actions Ubuntu 24.04 ppc64le/s390x cases don't work in fork repositories unlike GitHub Actions x86_64/arm64 pipelines. 
I add the new job "host-ibm", because there are ppc64le/s390x specific logic, `if: github.repository == 'ruby/fiddle'` and  "Set …
> CI: Add GitHub Actions ppc64le/s390x cases
